import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Providers } from './Providers'

// import localFont from 'next/font/local'
// const Cambridge = localFont({
// 	src: '/font/Cambridge.woff'
// })

const Montserrat_font = Montserrat({
	subsets: ['cyrillic', 'latin'],
	weight: '400'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${Montserrat_font.className} antialiased`}>
				<Providers>
					<main className="flex min-h-screen flex-col items-center justify-between">
						{children}
					</main>
				</Providers>
			</body>
		</html>
	)
}
